[workspace]

members = ["apps/*"]

[workspace.metadata.dist]
cargo-dist-version = "0.0.3"
rust-toolchain-version = "1.67.1"
ci = ["github"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin"]

[profile.dist]
inherits = "release"
lto = "thin"
